# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bargainflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commission',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('O', 'Opened'), ('B', 'Bidded'), ('A', 'Accepted'), ('F', 'Finished')], default='O', max_length=1),
        ),
    ]
