# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 16:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargainflow', '0002_auto_20170326_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 3, 26, 16, 32, 0, 194871)),
        ),
    ]
