# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 15:29
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bargainflow', '0004_auto_20170408_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 4, 9, 17, 29, 46, 733936)),
        ),
        migrations.AlterField(
            model_name='commissionbid',
            name='bidder_comment',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
