# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bargainflow', '0004_auto_20170408_2059'),
        ('bargainflow', '0004_auto_20170409_1406'),
    ]

    operations = [
    ]
