# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bargainflow', '0004_auto_20170409_1406'),
        ('bargainflow', '0005_auto_20170409_1729'),
    ]

    operations = [
    ]
