# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargainflow', '0005_merge_20170410_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 4, 10, 20, 40, 44, 362173)),
        ),
        migrations.AlterField(
            model_name='commissionbid',
            name='bidder_comment',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
