# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 19:32
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bargainflow', '0006_merge_20170410_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='PLN', max_digits=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar'), ('PLN', 'Zloty')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='commission',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 4, 19, 21, 32, 4, 940127)),
        ),
    ]
