# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargainflow', '0006_auto_20170410_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 4, 19, 22, 6, 37, 90931)),
        ),
    ]
