# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 20:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargainflow', '0007_auto_20170419_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 4, 19, 22, 22, 24, 780820)),
        ),
    ]
