# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:27
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bargainflow', '0007_auto_20170419_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 4, 21, 18, 27, 44, 163384)),
        ),
    ]
