# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bargainflow', '0008_auto_20170419_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='bid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='bargainflow.CommissionBid'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 4, 20, 10, 29, 48, 221961)),
        ),
    ]
