# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:59
from __future__ import unicode_literals

import datetime

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bargainflow', '0008_auto_20170421_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 4, 21, 18, 59, 1, 926325)),
        ),
        migrations.AlterUniqueTogether(
            name='commissionbid',
            unique_together=set([('bidder', 'commission')]),
        ),
    ]
