# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bargainflow', '0009_auto_20170420_1029'),
        ('bargainflow', '0009_auto_20170421_1859'),
    ]

    operations = [
    ]
