# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 20:34
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bargainflow', '0011_auto_20170422_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 5, 7, 22, 34, 36, 433724)),
        ),
    ]
