# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bargainflow', '0012_auto_20170507_2234'),
        ('bargainflow', '0012_auto_20170506_1107'),
    ]

    operations = [
    ]
