# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:37
from __future__ import unicode_literals

from decimal import Decimal

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bargainflow', '0013_merge_20170507_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=6, default=Decimal('0.0'), default_currency='LTC',
                                                   max_digits=10),
        ),
        migrations.AlterField(
            model_name='commission',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('LTC', 'Litecoin')], default='LTC', editable=False,
                                                      max_length=3),
        ),
    ]
