# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bargainflow', '0014_auto_20170508_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='commission',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
