# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bargainflow', '0015_auto_20170508_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='price',
        ),
    ]
