"""empty message

Revision ID: 12af170057d3
Revises: 
Create Date: 2018-05-21 14:36:55.086354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12af170057d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_stock_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_interval', sa.Interval(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alert_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['base_stock_alert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('high_value_stock_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('high_price_alert_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_stock_alert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('low_value_stock_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('low_price_alert_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_stock_alert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_alert_occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_alert_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['stock_alert_id'], ['base_stock_alert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_alert_occurrence')
    op.drop_table('low_value_stock_alert')
    op.drop_table('high_value_stock_alert')
    op.drop_table('alert_notification')
    op.drop_table('base_stock_alert')
    # ### end Alembic commands ###
