# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiatek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='name',
        ),
        migrations.AlterField(
            model_name='lightmeasurement',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='moisturemeasurement',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='temperaturemeasurement',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
