# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wybory2000.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('region_type', models.CharField(max_length=35)),
            ],
            bases=(models.Model, wybory2000.models._VotingRegion),
        ),
        migrations.CreateModel(
            name='VoteCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borough', models.CharField(max_length=8)),
                ('votes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory2000.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='VoteResultSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borough', models.CharField(max_length=8)),
                ('ballot_papers', models.PositiveIntegerField()),
                ('votes_valid', models.PositiveIntegerField()),
                ('votes_invalid', models.PositiveIntegerField()),
            ],
        ),
    ]
