# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 17:31
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stockexchange',
            unique_together=set([('codename', 'country')]),
        ),
        migrations.AddField(
            model_name='company',
            name='stock_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockhistory.StockExchange'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('code', 'stock_exchange')]),
        ),
        migrations.CreateModel(
            name='DownloadCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_download_hash', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('transaction_volume', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockhistory.Company', to_field='code')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='stockdata',
            index_together=set([('company', 'datetime')]),
        ),
    ]
