# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 17:32
from __future__ import unicode_literals

from django.db import migrations


def cache_init(apps, schema_editor):
    DownloadCache = apps.get_model('stockhistory', "DownloadCache")
    DownloadCache(last_download_hash="#").save()


class Migration(migrations.Migration):

    dependencies = [
        ('stockhistory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cache_init),
    ]
