# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 21:49
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockhistory', '0002_cache_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadcache',
            name='last_download_hash',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='value',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20),
        ),
    ]
