# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockhistory', '0003_extend_price_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='company',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='stockhistory.Company', to_field='code'),
        ),
    ]
