# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockhistory', '0004_add_company_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
