# Generated by Django 2.0.3 on 2018-04-30 14:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockhistory', '0005_add_date_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceTick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='DownloadCache',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='company',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='stockhistory.Company', to_field='code'),
        ),
        migrations.AlterField(
            model_name='stockexchange',
            name='codename',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='stockexchange',
            name='country',
            field=models.CharField(max_length=8),
        ),
        migrations.AddField(
            model_name='stockpricetick',
            name='company',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='stockhistory.Company', to_field='code', unique=True),
        ),
    ]
