# Generated by Django 2.0.3 on 2018-05-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockhistory', '0006_stock_price_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricetick',
            name='company',
            field=models.OneToOneField(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='stockhistory.Company', to_field='code'),
        ),
    ]
