# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneyflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('USD', 'USD')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneyflow.Wallet')),
            ],
        ),
    ]
