# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 18:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyflow', '0002_currencyaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='currencyaccount',
            unique_together=set([('currency', 'wallet')]),
        ),
    ]
