# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('moneyflow', '0003_auto_20170419_2132'),
        ('moneyflow', '0004_customer'),
    ]

    operations = [
    ]
