# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('moneyflow', '0006_moneytransaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyaccount',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='currencyaccount',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='moneytransaction',
            name='destination_wallet',
        ),
        migrations.RemoveField(
            model_name='moneytransaction',
            name='source_wallet',
        ),
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet',
                                    to='cc.Wallet'),
        ),
        migrations.DeleteModel(
            name='CurrencyAccount',
        ),
        migrations.DeleteModel(
            name='MoneyTransaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
