# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('moneyflow', '0008_add_currency_and_master_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallet',
        ),
    ]
