# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 16:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cc', '0010_withdrawtransaction_walletconflicts'),
        ('moneyflow', '0009_remove_customer_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet',
                                    to='cc.Wallet'),
            preserve_default=False,
        ),
    ]
